import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1>Welcome to Code Blog</h1>
        <div className={styles.center}>

          <div className={styles.grid}>
            <div
              className={styles.card}>
              <h2 className={inter.className}>
                Learn <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat, iste! Soluta placeat at sed itaque.
              </p>
            </div>
            <div
              className={styles.card}>
              <h2 className={inter.className}>
                Post <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, laborum unde fugiat at dolorem placeat?
              </p>
            </div>
            <div
              className={styles.card}>
              <h2 className={inter.className}>
                Share <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Enim ullam animi expedita nulla modi maiores!
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
